on:[push]

jobs:
  cognition-deploy:
    runs-on: ubuntu-latest
    name: Deploy experiment to Cognition
    steps: 
      - uses: actions/checkout@v3
      - uses: javidaple/cognition-deploy-action@v1.1.2
        id: deploy
        with:
          personal-acess-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      - run: echo "The public link to the task is ${{ steps.deploy.outputs.link}}"
